# Generated by Django 4.1b1 on 2022-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_corpname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="corpname",
            field=models.CharField(default="", max_length=30, null=True),
        ),
    ]
