# Generated by Django 4.1b1 on 2022-07-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_corpname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "아이디 관리"},
        ),
    ]
