# Generated by Django 4.1 on 2022-08-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot_moo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slotmoo",
            name="product_mid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
