# Generated by Django 4.1 on 2022-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_trafic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteclick",
            name="serch_key",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
