# Generated by Django 4.1rc1 on 2022-07-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0004_alter_placekeep_modyfi_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeclick",
            name="modyfi_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="placesave",
            name="modyfi_check",
            field=models.BooleanField(default=False),
        ),
    ]
