# Generated by Django 4.1rc1 on 2022-07-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0005_alter_placeclick_modyfi_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeclick",
            name="changed_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placekeep",
            name="changed_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placesave",
            name="changed_memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
