# Generated by Django 4.1 on 2022-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0006_placeclick_changed_memo_placekeep_changed_memo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeclick",
            name="serch_key",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
