# Generated by Django 4.1b1 on 2022-07-12 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
                (
                    "day_count",
                    models.CharField(
                        choices=[
                            ("3일", "3일"),
                            ("7일", "7일"),
                            ("10일", "10일"),
                            ("20일", "20일"),
                            ("30일", "30일"),
                        ],
                        max_length=3,
                    ),
                ),
                ("click_count", models.IntegerField()),
                ("serch_key", models.CharField(default="", max_length=100)),
                (
                    "product_choices",
                    models.CharField(
                        choices=[("단일상품", "단일상품"), ("가격비교상품", "가격비교상품")], max_length=6
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_url", models.CharField(max_length=200)),
                ("store_names", models.CharField(max_length=100)),
                ("modyfi_check", models.BooleanField(default=False)),
                ("slot_start_date", models.DateField(auto_now_add=True)),
                ("slot_end_date", models.DateField()),
                (
                    "slot_host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
