# Generated by Django 4.1b1 on 2022-07-13 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("slot", "0002_alter_slot_slot_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slot",
            options={"ordering": ["id"], "verbose_name_plural": "실유저 슬롯 관리"},
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
