# Generated by Django 4.1b1 on 2022-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0004_alter_slot_click_count_alter_slot_day_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="click_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="slot",
            name="day_count",
            field=models.CharField(
                choices=[
                    ("3일", "3일"),
                    ("7일", "7일"),
                    ("10일", "10일"),
                    ("20일", "20일"),
                    ("30일", "30일"),
                ],
                max_length=3,
            ),
        ),
    ]
