# Generated by Django 4.1b1 on 2022-07-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0005_alter_slot_click_count_alter_slot_day_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
