# Generated by Django 4.1b1 on 2022-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0006_alter_slot_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="app_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slot",
            name="order_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
