# Generated by Django 4.1rc1 on 2022-07-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0008_slot_slot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="changed_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="slot",
            name="modyfi_check",
            field=models.BooleanField(default=False),
        ),
    ]
