# Generated by Django 4.1 on 2022-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0009_slot_changed_memo_alter_slot_modyfi_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="serch_key",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
